# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-15 18:59
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180215_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='data_dump',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='risk',
            name='fields',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
